# Generated by Django 4.0.3 on 2022-08-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='json',
            field=models.JSONField(default=None, null=True, verbose_name='JSON'),
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.JSONField(default=None, null=True, verbose_name='Template'),
        ),
    ]
