# Generated by Django 4.0.3 on 2022-08-20 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='project',
        ),
        migrations.RemoveField(
            model_name='product',
            name='project',
        ),
        migrations.AddField(
            model_name='page',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to=settings.AUTH_USER_MODEL, verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
